# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mGHS <- function(B, bn, n, S, p, hyp_ta, chain = 0L, ping = 1000L) {
    .Call(`_mGHS_mGHS`, B, bn, n, S, p, hyp_ta, chain, ping)
}

mGHS_new <- function(B, bn, n, S, p, hyp_ta, chain = 0L, ping = 1000L) {
    .Call(`_mGHS_mGHS_new`, B, bn, n, S, p, hyp_ta, chain, ping)
}

pbdv <- function(va, x) {
    .Call(`_mGHS_pbdv`, va, x)
}

rIW <- function(df, S, K) {
    .Call(`_mGHS_rIW`, df, S, K)
}

rg3p_c1 <- function(a, b) {
    .Call(`_mGHS_rg3p_c1`, a, b)
}

rg3p_approx <- function(a, b, c) {
    .Call(`_mGHS_rg3p_approx`, a, b, c)
}

rg3p <- function(a, b, c) {
    .Call(`_mGHS_rg3p`, a, b, c)
}

pgamma3p1 <- function(x, a, b) {
    .Call(`_mGHS_pgamma3p1`, x, a, b)
}

